config/routes.rb
YApp::Application.routes.draw do
  resources :plots

  require 'resque/server'

  resources :users, :user_sessions
   match 'login' => 'user_sessions#new', :as => :login
   match 'logout' => 'user_sessions#destroy', :as => :logout
   
   match 'eval' => 'phrases/1/edit', :as => :eval
   
   
  resources :judges

  get "connotation/create"

  get "connotation/edit"

  get "connotation/update"

  resources :metawords

  resources :phrases

  resources :corpus_comments

  resources :words
  
  resources :evaluation

  resources :videos
  mount Resque::Server.new, :at => "/resque"
  root :to => "plots#index", :as => :homepage

 

end

app/models/metaword.rb
class Metaword < ActiveRecord::Base

  has_many :memberships
  has_many :videos, :through => :memberships

  def self.load_all_keywords
#    Video.destroy_all "comments = '--- []\n'"
#    videos_with_non_nil_comments = Video.find_all_by_download(true)
    videos_with_non_nil_comments = Video.find(:all, :conditions => "comments IS NOT NULL")
    videos_with_non_nil_comments.each do |v|
      if !v.keywords.nil?
        kw = v.keywords.split("\n- ")
        kw.delete("---")
        kw.each do |k|
          k = k.gsub(/\n/,'')
          k = k.gsub(/'/,'')
          k = k.downcase
          kwd = Metaword.find_by_content(k)          
          if kwd.nil?
            mw = Metaword.create!
            mw.content = k
            mw.youtubeid = v.content
            mw.videos << v
            mw.save!
          else
            kwd.youtubeid << v.content
            kwd.videos << v
            kwd.save!
          end
        end
      end
    end
    # Metaword.all.each do |m|
    #   redundant_array = Array.new
    #   redundant_array = Metaword.find_all_by_content(m.content)
    #   redundant_array.delete(m)
    #   redundant_array.each do |r|
    #     m.videos += r.videos
    #     m.youtubeid += r.youtubeid
    #     Metaword.find_all_by_content(r.content).destroy
    #     m.save!
    #   end
    # end
  end

 

end

app/controllers/metawords_controller.rb
class MetawordsController < ApplicationController
  # GET /metawords
  # GET /metawords.json
  def index
    @metawords = Metaword.order(:id).page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @metawords }
    end
  end

  # GET /metawords/1
  # GET /metawords/1.json
  def show
    @metaword = Metaword.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @metaword }
    end
  end

  # GET /metawords/new
  # GET /metawords/new.json
  def new
    @metaword = Metaword.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @metaword }
    end
  end

  # GET /metawords/1/edit
  def edit
    @metaword = Metaword.find(params[:id])
  end

  # POST /metawords
  # POST /metawords.json
  def create
    @metaword = Metaword.new(params[:metaword])

    respond_to do |format|
      if @metaword.save
        format.html { redirect_to @metaword, notice: 'Metaword was successfully created.' }
        format.json { render json: @metaword, status: :created, location: @metaword }
      else
        format.html { render action: "new" }
        format.json { render json: @metaword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /metawords/1
  # PUT /metawords/1.json
  def update
    @metaword = Metaword.find(params[:id])

    respond_to do |format|
      if @metaword.update_attributes(params[:metaword])
        format.html { redirect_to @metaword, notice: 'Metaword was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @metaword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /metawords/1
  # DELETE /metawords/1.json
  def destroy
    @metaword = Metaword.find(params[:id])
    @metaword.destroy

    respond_to do |format|
      format.html { redirect_to metawords_url }
      format.json { head :ok }
    end
  end
end

app/helpers/metawords_helper.rb
module MetawordsHelper
end

app/views/metawords/_form.html.erb
<%= form_for(@metaword) do |f| %>
  <% if @metaword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@metaword.errors.count, "error") %> prohibited this metaword from being saved:</h2>

      <ul>
      <% @metaword.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :youtubeid %><br />
    <%= f.text_field :youtubeid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/metawords/edit.html.erb
<h1>Editing metaword</h1>

<%= render 'form' %>

<%= link_to 'Show', @metaword %> |
<%= link_to 'Back', metawords_path %>

app/views/metawords/index.html.erb
<h1>Listing metawords</h1>
<%= paginate @metawords %> 

<table>
  <tr>
    <th>Content</th>
    <th>Youtubeid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @metawords.each do |metaword| %>
  <tr>
    <td><%= metaword.content %></td>
    <td><%= metaword.youtubeid %></td>
  </tr>
<% end %>
</table>

app/views/metawords/new.html.erb
<h1>New metaword</h1>

<%= render 'form' %>

<%= link_to 'Back', metawords_path %>

app/views/metawords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @metaword.content %>
</p>

<p>
  <b>Youtubeid:</b>
  <%= @metaword.youtubeid %>
</p>


<%= link_to 'Edit', edit_metaword_path(@metaword) %> |
<%= link_to 'Back', metawords_path %>