config/routes.rb
YApp::Application.routes.draw do
  resources :plots

  require 'resque/server'

  resources :users, :user_sessions
   match 'login' => 'user_sessions#new', :as => :login
   match 'logout' => 'user_sessions#destroy', :as => :logout
   
   match 'eval' => 'phrases/1/edit', :as => :eval
   
   
  resources :judges

  get "connotation/create"

  get "connotation/edit"

  get "connotation/update"

  resources :metawords

  resources :phrases

  resources :corpus_comments

  resources :words
  
  resources :evaluation

  resources :videos
  mount Resque::Server.new, :at => "/resque"
  root :to => "plots#index", :as => :homepage

 

end

app/views/layouts/application.html.erb
	<!DOCTYPE html>
	<html lang="en">
	  <head>
	    <meta charset="utf-8">
	    <title>pULLR</title>
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	    <meta name="description" content="">
	    <meta name="author" content="">

	    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
	    <!--[if lt IE 9]>
	      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	    <![endif]-->

	    <!-- Le styles -->



	<%= stylesheet_link_tag "bootstrap", "docs.css", "bootstrap-responsive.css" %>

	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>

	    <!-- Le fav and touch icons -->
	    <link rel="shortcut icon" href="assets/ico/favicon.ico">
	    <link rel="apple-touch-icon" href="assets/ico/apple-touch-icon.png">
	    <link rel="apple-touch-icon" sizes="72x72" href="assets/ico/apple-touch-icon-72x72.png">
	    <link rel="apple-touch-icon" sizes="114x114" href="assets/ico/apple-touch-icon-114x114.png">
	  </head>

	  <body data-spy="scroll" data-target=".subnav" data-offset="50">


	  <!-- Navbar
	    ================================================== -->
	    <div class="navbar navbar-fixed-top">
	      <div class="navbar-inner">
	        <div class="container">
	          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </a>
	         <a class="brand" href="./index.html">pULLr</a>
	                       	<div class="nav-collapse">
	                      		<ul class="nav">

	                        <li class="">
	                          <a href="./download.html">Videos</a>
	                        </li>
	                        <li class="">
	                          <a href="./examples.html">About</a>
	              </li>
	            </ul>
	          </div>
	        </div>
	      </div>
	    </div>

	    <div class="container">



 
<%= yield %>

 <!-- Footer
  ================================================== -->
  <footer class="footer">
    <p class="pull-right"><a href="#">Back to top</a></p>
    project ULLr 2012 </p>
            <p>Code licensed under the <a href="http://www.apache.org/licenses/LICENSE-2.0" target="_blank">Apache License v2.0</a>. Documentation licensed under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</p>
            
  </footer>

</div><!-- /container -->



<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
<script src="assets/js/jquery.js"></script>
<script src="assets/js/google-code-prettify/prettify.js"></script>
<script src="assets/js/bootstrap-transition.js"></script>
<script src="assets/js/bootstrap-alert.js"></script>
<script src="assets/js/bootstrap-modal.js"></script>
<script src="assets/js/bootstrap-dropdown.js"></script>
<script src="assets/js/bootstrap-scrollspy.js"></script>
<script src="assets/js/bootstrap-tab.js"></script>
<script src="assets/js/bootstrap-tooltip.js"></script>
<script src="assets/js/bootstrap-popover.js"></script>
<script src="assets/js/bootstrap-button.js"></script>
<script src="assets/js/bootstrap-collapse.js"></script>
<script src="assets/js/bootstrap-carousel.js"></script>
<script src="assets/js/bootstrap-typeahead.js"></script>
<script src="assets/js/application.js"></script>

</body>
</html>

<!--
<html>
<head>
  <title>AUV Project</title>
  <div id="nav"  style ="border:2px solid green; width:300px; padding: 20px; background: #99ccff">
	<%= link_to "View registered users", users_path, {:style=>'color:blue'} %> |
	
       <% if current_user %>
       <%= link_to "Edit Profile", edit_user_path(current_user.id)%>
       <%= link_to "Logout", :logout%>
       <% else %>
   	   <%= link_to "Register", new_user_path, {:style=>'color:purple'}%>  | 
        <%= link_to "Login", :login, {:style=>'color:green'} %> 
       <% end %>
   </div>	<br />
<div style ="border:2px solid green; width:300px; padding: 20px; background: #fffccc">
<h2>	<%= link_to "Rate the comments", :homepage %></h2></div><br />
<div style ="border:2px solid green; width:300px; padding: 20px; background: #cccfff">
<font color="red"><%= link_to "Request videos", plots_path, {:style=>'color:red'} %> </font></div><br />
	
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	
 
<%= yield %>

</body>
</html>
-->